### PR TITLE
Handling case where sys.stdin encoding is None

### PR DESCRIPTION
**Pull request by stefanoborini**
When running under supervisord, `sys.stdin.encoding` is None, resulting in a silent exception.
Use the default encoding as a fallback.

### CODE REVIEW

**Comment by stefanoborini** [comment]
Currently untested as I would have to add mock to the requirements and mock out sys.stdin.encodings. Please let me know if that's ok.

**Comment by stefanoborini** [comment]
Failure on py3.5 unrelated.

**Comment by ergoithz** [comment]
Please pull from master, tests should pass now.

**Comment by ergoithz** [comment]
Thanks!

**Pull request merged**
